{
 "title": "StatefulSet Debug",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_statefulset_status_replicas_current, exported_namespace)"
    }
   },
   {
    "name": "statefulset",
    "query": {
     "query": "label_values(kube_statefulset_status_replicas_current{exported_namespace=~\"$namespace\"}, statefulset)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Out of Date Replicas",
   "type": "state-timeline",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "avg(kube_statefulset_replicas{statefulset=~\"$statefulset\"} - kube_statefulset_status_replicas_updated{statefulset=~\"$statefulset\"}) by (exported_namespace, statefulset) > 0",
     "legendFormat": "{{exported_namespace}}/{{ statefulset }}"
    }
   ]
  },
  {
   "title": "Replicas (spec)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "avg(kube_statefulset_replicas{statefulset=~\"$statefulset\"}) by (statefulset)",
     "legendFormat": "{{ statefulset }}"
    }
   ]
  },
  {
   "title": "Replicas (Updated)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "avg(kube_statefulset_status_replicas_updated{statefulset=~\"$statefulset\"}) by (statefulset)",
     "legendFormat": "{{ statefulset }}"
    }
   ]
  },
  {
   "title": "Replicas (Available)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 9 },
   "targets": [
    {
     "expr": "avg(kube_statefulset_status_replicas_available{statefulset=~\"$statefulset\"}) by (statefulset)",
     "legendFormat": "{{ statefulset }}"
    }
   ]
  },
  {
   "title": "Replicas (Ready)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 9 },
   "targets": [
    {
     "expr": "avg(kube_statefulset_status_replicas_ready{statefulset=~\"$statefulset\"}) by (statefulset)",
     "legendFormat": "{{ statefulset }}"
    }
   ]
  },
  {
   "title": "Rarely Useful Charts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Replicas (Current)",
     "type": "timeseries",
     "description": "This chart is of questionable usability because it will show StatefulSets with the `OnDelete` policy. The `OnDelete` policy never updates the `currentRevision` by design, since it's never actually doing any updates, so these (after the first restart/update) will **always** show \"non-current\".\n\nFor normal StatefulSets, this effectively shows time periods when they're updating, however this is also available in the \"Out of Date\" replicas chart.",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
     "targets": [
      {
       "expr": "avg(kube_statefulset_status_replicas_current{statefulset=~\"$statefulset\"}) by (statefulset)",
       "legendFormat": "{{ statefulset }}"
      }
     ]
    },
    {
     "title": "Non-Current Replicas",
     "type": "state-timeline",
     "description": "This chart is of questionable usability because it will show StatefulSets with the `OnDelete` policy. The `OnDelete` policy never updates the `currentRevision` by design, since it's never actually doing any updates, so these (after the first restart/update) will **always** show \"non-current\".\n\nFor normal StatefulSets, this effectively shows time periods when they're updating, however this is also available in the \"Out of Date\" replicas chart.",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
     "targets": [
      {
       "expr": "avg(kube_statefulset_status_replicas{statefulset=~\"$statefulset\"} - kube_statefulset_status_replicas_current{statefulset=~\"$statefulset\"}) by (exported_namespace, statefulset) > 0",
       "legendFormat": "{{ exported_namespace }}/{{ statefulset }}"
      }
     ]
    },
    {
     "type": "text",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 28 },
     "options": {
      "content": "### Current Replicas\n\n\nThis chart is of questionable usability because it will show StatefulSets with the\n`OnDelete` policy. The `OnDelete` policy never updates the `currentRevision` by\ndesign, since it's never actually doing any updates, so these (after the first\nrestart/update) will **always** show \"non-current\".\n\nFor normal StatefulSets, this effectively shows time periods when they're updating,\nhowever this is also available in the \"Out of Date\" replicas chart.\n\n### Replicas (Status)\n\nThis is always the same as Replicas from the Spec, but it relies on a status field\ninstead of getting it from the spec. There might be a rare case where this is\ndifferent/useful, but I haven't found it yet. That's why this panel is down here."
     }
    },
    {
     "title": "Replicas (status)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 28 },
     "targets": [
      {
       "expr": "avg(kube_statefulset_status_replicas{statefulset=~\"$statefulset\"}) by (statefulset)",
       "legendFormat": "{{ statefulset }}"
      }
     ]
    }
   ]
  }
 ]
}